### ISSUE TITLE
Intervention Image

### ISSUE THREAD

**Issue by grafikkaos** [plank/laravel-mediable#10]
Hi,

Came across your package and I have to say it has been a time save when it comes to uploading media files for different models. Many thanks for that.

I have a small question, I am trying to generate thumbnail for images that are uploaded and the intervention image class is my go to class when resizing images.  While I can write the code to generate the thumbnails to individual folders / disks, is there a way I can tap into this using your package?

For example when uploading files, the **fromSource** method is used.  Is there a method that I can use to upload a generated thumbnail e.g **MediaUploaded::fromFile($thumbnail)->upload()**. $thumbnail coming from something like **$thumbnail = Image::make('foo.jpg')->resize(300, 200);**

Any thoughts would be great!

Thanks

Emmanuel

**Comment by frasmage** [comment]
Hi @grafikkaos,

First of all, thanks for your interest in this project! I'm glad you are enjoying it.

As for your question, the `MediaUploader::fromFile()` method can accept a number of different inputs, including absolute file paths. You could do something like this:

```php
$tmp = tempnam(sys_get_temp_dir(),'image'); // store in a temporary location
rename($tmp, $tmp = $tmp . '.jpg'); //uploader needs an extension to read
$image = Image::make($media->getAbsolutePath())
	->resize(300, 200)
	->save($tmp);

MediaUploader::fromSource($tmp)
	->toDestination($disk, 'thumbnails')
	->upload();
```

If you are dealing with particularly large files and moving from tmp to disk is a speed issue, you could have intervention place the file directly on the disk and then populate the `Media` record yourself.

```php
$path = public_path('uploads/thumbnails');
$image = Image::make($media->getAbsolutePath())
	->resize(300, 200)
	->save($path);

$thumb = new Media;
$thumb->disk = 'uploads';
$thumb->directory = 'thumbnails';
$thumb->filename = $media->getKey();
$thumb->extension = 'jpg';
$thumb->mime_type = 'image/jpeg';
$thumb->aggregate_type = Media::TYPE_IMAGE;
$thumb->size = filesize($path);
$thumb->save();
```

If you need to maintain the association of the `Media` to its thumbnail, the implementation is entirely up to you – there is no single right answer here. You could save all thumbnails under the key of the original model (as in my example above), subclass `Media` and give a hasOne relationship to itself, etc.

A completely different approach that I have used for resizing media is [League/Glide](https://github.com/thephpleague/glide), which resizes images on the fly based on HTTP query parameters and handles its own caching. The advantage here is that you don't need to duplicate your Media records and it can spit out any number of sizes on the fly.

You are not the first to mention having a means to import images being output by resizing package.  I don't have any intention of adding built-in support for any one package or tool, since I would rather keep this package open-ended and let each users' use case dictate implementation, but I might add some functions to make something like approach 2 above easier to implement.

**Comment by grafikkaos** [comment]
Hi @frasmage ,

Thanks for the swift response.  I will look into using League/Glide to have the thumbnails generated. However if and when you do decide to implement a function to make importing images easier, that would be great and I will be paying great to the updates with this package.

Many thanks again :+1:
