### ISSUE TITLE
RemoteUrlAdapter->Valid() not work properly

### ISSUE THREAD

**Issue by PayteR** [plank/laravel-mediable#103]
Hi, when i want to download this image

https://s-media-cache-ak0.pinimg.com/originals/9a/66/f7/9a66f7c67c435eb126ee270ca7598db1.gif

is there redirect, than triggers not valid image on RemoteUrlAdapter->Valid()

here are headers returned from server

![image](https://user-images.githubusercontent.com/1248565/38193430-5800ac2c-3672-11e8-87b7-afb54960e9d6.png)

i will create quick fix for this in a minute, but it's just quick fix, you need to implement it better...

**Comment by frasmage** [comment]
Hi @PayteR,

Another good find. 

You solution would work as a patch, though it might be better to iterate through a while loop (e.g. what if there are four redirects?) and break if you find an index that is not set or not 300-level.

Also, the mimeType() and size() methods are reading headers that are now arrays instead of scalars. So we would need to adjust those to read the last entry.

Would you like me to leave the PR to you, so that you get the credit for it?

**Comment by frasmage** [comment]
Scratch that about mimeType/size, the getHeader() method already accounts for arrays.

**Comment by PayteR** [comment]
for while...loop there needs to be more refactoring done, and i don't know, how much can i change in that methods. You will find better while...loop solution faster.

**Comment by simonschaufi** [comment]
@frasmage I have the exact same problem with facebook avatars returned by the graph api. The first status code they return is `302 Found` and the next one `200 OK`.

`get_headers` returns this:
```
0 => 'HTTP/1.1 302 Found'
1 => 'HTTP/1.1 200 OK'
```
