### ISSUE TITLE
Aggregate Type and mime_type with m3u8

### ISSUE THREAD

**Issue by Surt** [plank/laravel-mediable#154]
When executing `MediaUploader::update($media)` over a `m3u8` file the result in database is:

mime_type = `text/plain`
aggregate_type = 'document' 

I did add the extension to the mediable types 

```php 
        Plank\Mediable\Media::TYPE_VIDEO        => [
            'mime_types' => [
                'video/mp4',
                'video/mpeg',
                'video/ogg',
                'video/webm',
                'application/x-mpegURL'
            ],
            'extensions' => [
                'mp4',
                'm4v',
                'mov',
                'ogv',
                'webm',
                'm3u8'
            ]
```

but it takes second place instead of first on this code:

` MediaUploader:429`
```php 
// typesForMime = 'document'
// typesForExtension = 'video'
$merged = array_merge($typesForMime, $typesForExtension);
$type = reset($merged);  // 'document'
```

Since the one from Extension is the one that I added at the `config/mediable` it would be great to take precedence over the auto-discovered.

` MediaUploader:429`
```php 
// typesForMime = 'document'
// typesForExtension = 'video'
$merged = array_merge($typesForExtension, $typesForMime);
$type = reset($merged);  // 'video'
```

As for the "mime_type" it fully depends on Flysystem and Symfony so nothing we can do.

**Comment by frasmage** [comment]
Hi @Surt,

The mime type is more trusted than extension sign it is inferred from the contents of the file instead of being an arbitrary suffix which anyone can freely modify.

I think you should try to find the right mime type that your server would recognize this m3u8 file as. I'm not particularly familiar with the format, but from a quick google search, I can see that `application/vnd.apple.mpegurl` and `application/mpegurl` are possible alternatives. Also, try entering the existing mime value in lowercase (`application/x-mpegurl`).
