### ISSUE TITLE
Change the order of lines in the replace method from MediaUploader

### ISSUE THREAD

**Issue by siarheipashkevich** [plank/laravel-mediable#157]
There is a problem with removing file before moving to new destination in this line:
https://github.com/plank/laravel-mediable/blob/master/src/MediaUploader.php#L545
Could you please move this line below after file moving to new destination?

**Comment by frasmage** [comment]
Hi @siarheipashkevich,

Can you please provide more details about what you are trying to do and why this is causing you a problem? I'm not following what you are asking as swapping those lines would result in deleting the media file you just uploaded.

**Comment by siarheipashkevich** [comment]
Hi @frasmage 

I'll try to explain my problem.

The user upload media file to `public` disk, then this media file passed to queue job which shoul move this media from `public` disk to `cloud` space. The code of the job:

```
$media = $this->media;

$url = Storage::disk($media->disk)->url($media->getDiskPath());

MediaUploader::fromSource($url)->toDisk(config('filesystems.default'))->replace($media);
```

And in the `replace` method I'm getting an error that the file not found (because file deleted firstly).
The code error:
```
ErrorException: fopen(https://test.com/storage/orders/122019/team_from_1/image.jpg): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found
 in /home/forge/test.com/vendor/plank/laravel-mediable/src/SourceAdapters/RemoteUrlAdapter.php:92
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'fopen(https://t...', '/home/forge/api...', 92, Array)
#1 /home/forge/test.com/vendor/plank/laravel-mediable/src/SourceAdapters/RemoteUrlAdapter.php(92): fopen('https://tes...', 'rb')
#2 /home/forge/test.com/vendor/plank/laravel-mediable/src/MediaUploader.php(941): Plank\Mediable\SourceAdapters\RemoteUrlAdapter->getStreamResource()
#3 /home/forge/test.com/vendor/plank/laravel-mediable/src/MediaUploader.php(547): Plank\Mediable\MediaUploader->writeToDisk(Object(App\Models\Media))
#4 /home/forge/test.com/app/Jobs/UploadMediaToCloud.php(57): Plank\Mediable\MediaUploader->replace(Object(App\Models\Media))
#5 [internal function]: App\Jobs\UploadMediaToCloud->handle()
```

**Comment by frasmage** [comment]
Ok, I see what you are trying to do. This is actually a bug in your code. Effectively you are trying to replace a file with itself, which of course doesn't work because replacing deletes the original file. Replace is intended to be used to take a new file, overwriting an old file, but maintaining the same mediable relations (e.g. providing a new version of an attachment, without changing all of the places that it is attached).

What I think you actually want to do is move where the file is hosted, while keeping the same mediable relations. Aside from the deleting you mentioned, what you are doing _could_ work, though it is inefficient, since you are effectively re-uploading the file to your server from itself. What you want is a move operation, not an upload operation.

Unfortunately, The existing `$media->move()` and `$media->copy()` methods currently only support moving within the same disk. It sounds like you want some kind of `$media->moveToDisk()` method. I am happy to add that to this package, though I am not sure when I will have some time to do so myself. In the meantime, I would highly encourage you to open a PR adding such methods to the Media and MediaMover classes.

**Comment by siarheipashkevich** [comment]
@frasmage I got you. But I think it won't break anything if we change the order and we can use it to move between disks as well.

**Comment by siarheipashkevich** [comment]
@frasmage could you please answer me?

**Comment by frasmage** [comment]
Hi @siarheipashkevich, 

As I mentioned, I disagree with changing the order of the of these operations. The order is intentional to perform validation before taking the irreversible destructive action of deleting the original file. What you are trying to do is not the intended behaviour of that method, and really not efficient way to perform that operation.

I will try to work on a proper moveToDisk implementation at some point this week.

**Comment by frasmage** [comment]
Version 4.3.0 published adding support for `$media->moveToDisk()`. You shouldn't need to use the uploader at all for this operation any more.

**Comment by siarheipashkevich** [comment]
@frasmage thanks a lot
