### ISSUE TITLE
How to fix error when use laravel 7 

### ISSUE THREAD

**Issue by huylong** [plank/laravel-mediable#168]
affter read document in https://laravel-mediable.readthedocs.io/en/latest/uploader.html
I upload image error
``` 
$media = MediaUploader::fromSource($request->file('image'))
            ->toDestination('uploads', 'blog/thumbnails')
            ->upload();
```
BadMethodCallException
Method Illuminate\Http\UploadedFile::getClientSize does not exist.

**Comment by nfatiheralp** [comment]
If you want a quick solution;

Change the size () method in the UploadFileAdapter file as follows.

` public function size(): int
    {
        return (int) $this->source->getSize();
    }`

getClientSize() method is deprecated in symphony. You can use ->getSize() method instead of getClientSize(). Because UploadedFile class extend from SplFileInfo class and SplFileInfo has getSize method.

I hope it will help.

**Comment by huylong** [comment]
> If you want a quick solution;
> 
> Change the size () method in the UploadFileAdapter file as follows.
> 
> ` public function size(): int { return (int) $this->source->getSize(); }`
> 
> getClientSize() method is deprecated in symphony. You can use ->getSize() method instead of getClientSize(). Because UploadedFile class extend from SplFileInfo class and SplFileInfo has getSize method.
> 
> I hope it will help.

Thank you @nfatiheralp

**Comment by frasmage** [comment]
Thanks for bringing this to my attention. I have pushed a new patch version (4.2.1) fixing that deprecation notice.
