### ISSUE TITLE
Error Undefined class constant 'ON_DUPLICATE_REPLACE'

### ISSUE THREAD

**Issue by thandonguocmo2020** [plank/laravel-mediable#17]
I get the same error when using this command section 

up class : 

use MediaUploader;
use Plank\Mediable\Media;
----------------------------------------------

 $media = MediaUploader::fromSource($request->file('image'))  
              ->setDirectory('/avatar/demo')    
             ->setOnDuplicateBehavior(Media::ON_DUPLICATE_REPLACE)
             ->upload();
---------------------------------------------------------------
resuft => Undefined class constant 'ON_DUPLICATE_REPLACE'

**Comment by cyrulik** [comment]
Should be:
```php
->setOnDuplicateBehavior(MediaUploader::ON_DUPLICATE_REPLACE)
```
This constant doesn't exist on Media class.

**Comment by jdhmtl** [comment]
Haven't had much of a chance to look into this until now, but I'm reopening this because it's a legit bug. The typo in the docs was an issue for sure, but the underlying bug remains. `MediaUploader` returns the façade, not the underlying class, and `__callStatic` calls underlying methods but not calls to class constants, hence why `MediaUploader::ON_DUPLICATE_REPLACE` blows up. Easy enough to inject a helper class that would return the constant values for us. Thoughts?

**Comment by frasmage** [comment]
`\MediaUploader` is the default façade, as suggested in the docs, though this can be customized in config/app.php. `\Plank\Mediable\MediaUploader` is the class itself. Any constants should reference the class and not the façade. I realize that 'using' one means the other needs to be referenced explicitly or given a use as alias.

**Comment by jdhmtl** [comment]
Might it be worth making the examples in the docs more explicit, then?

`use MediaUploader` suggests the façade is being used, which is what led to this confusion in the first place.
