### ISSUE TITLE
Strange query when eager loading

### ISSUE THREAD

**Issue by dsazup** [plank/laravel-mediable#221]
Hey, great package! Everything is fine but I wanted to check if this query is expected, or is this a bug? If it's expected, do you know why it's there? 🤔 

![Screenshot 2020-10-24 at 11 45 55](https://user-images.githubusercontent.com/8631224/97079797-a0da6880-15ee-11eb-9949-4bec15da400f.png)

I get this when I do `MyModel::withMediaAndVariants()`. Seems like it's coming from this line: 
https://github.com/plank/laravel-mediable/blob/1fa77f27214a80517b67355a21dde5b00cf49d5c/src/Mediable.php#L129

**Comment by frasmage** [comment]
Hi @dsazup,

That with line is intentional. A variant family is a set containing one original and N variants. Variants and originals are all fully functional Media. The package does not impose any kind of restriction on what can be done with them, i.e. you can just as easily attach an original as a variant to a mediable model. In order to ensure that the variant helper methods (`getVariant()`) always work efficiently regardless of what you are starting from, the library loads both the variants of the current model (assuming it is the original) and the variants of the original of the current model (assuming it is a variant).

That dud query seems to be the result of how Laravel handles these eager load queries internally. It seems when there are no relevant entries, instead of skipping the running the query at all, it neuters it with that condition (https://github.com/laravel/framework/blob/8.x/src/Illuminate/Database/Query/Grammars/Grammar.php#L271). Unfortunately, this results in needing to do an extra unnecessary roundtrip to the database, which might cost you a few ms depending on your network, but it shouldn't have any impact on the database.

**Comment by dsazup** [comment]
Thank you for a thorough explanation and a link to the code that does it. It makes total sense 👍
