### ISSUE TITLE
FileNotFoundException on importPath( )

### ISSUE THREAD

**Issue by GeoSot** [plank/laravel-mediable#225]
Hello and many thanks for your efforts

I am not sure if i am mistaken but I get an FileNotFoundException _(Mediauploader line:640)_,
when I use the **MediaUploader** `importPath('public', 'someFileName')`

As i debug the whole process, it continues till line:639, where it hits the wall  on check `(!$storage->has($model->getDiskPath())) `

```php 

$diskPath= $model->getDiskPath()
$diskPath=absolutePath\laravel\storage\app/public\11_2020/dummy.png

```

While I was getting deeper I reached the  vendor/league/flysystem/src/Adapter/Local.php:122
on 'has' method where the $location sting became like the following:

`absolutePath\laravel\storage\app/public\absolutePath/laravel/storage/app/public/11_2020/dummy.png`

I tried to add the following on the 'importPath()' method before it calls the 'import()':

```php
$directory= str_replace($this->filesystem->disk($disk)->path(''),'',$directory);
```

and it does the job. But I don't know if it is the proper solution

May have any advice on this?

**Comment by frasmage** [comment]
Hi Geosot,

First, what's going on with those file paths? I'm very confused by the alternating `/` and `\` separators. Are you just typing that out freehand?

I'm pretty sure that your problem is that you are passing the absolute path to the $path parameter of the importPath method. You should instead be passing the path _relative to the disk root_. In your example, you should just do `$uploader->importPath('public', '11_2020/dummy.png')`.

**Comment by GeoSot** [comment]
it was an a windows system, and it messes the slashes, but works, fine.

Yes you are right, I wasn't passing the relative path.

thank you
