### ISSUE TITLE
Could not recognize source, `` provided.

### ISSUE THREAD

**Issue by Xoshbin** [plank/laravel-mediable#242]
Hi, I'm trying to save a file a "PDF file" with Livewire and Mediable library together. but it's throwing the error in the title above. my code is below.

```
$directory = "$year/$month/$day";

        Storage::makeDirectory('files/' . $directory, 0755, true, true);

        $newFile = $this->file->store($directory.'/files');

        $media = MediaUploader::fromSource($newFile)->toDirectory('files/' . $directory)->onDuplicateIncrement()->upload();
```

I had this issue before with image files but I have fixed it with image intervention library just like the code below. but for PDF files or a document file it's not working and giving errors:

```
$directory = "$year/$month/$day";

        Storage::makeDirectory('photos/' . $directory, 0755, true, true);

        $image = Image::make($this->photo);
        $image->save(time() . '-' . '.jpg');
        $saved_image_uri = $image->dirname . '/' . $image->basename;
        $media = MediaUploader::fromSource(new File($saved_image_uri))->toDirectory('photos/' . $directory)->onDuplicateIncrement()->upload();
```

Thank you

**Comment by frasmage** [comment]
Hi @Xoshbin,

It looks like your issue is that you are storing the file before passing it to the uploader, which is redundant. You should be able to pass `$this->file` (an `UploadedFile` object) directly to `MediaUploader::fromSource()`. For you latter example, you don't need to use Intervention just to rename a file! If you actually need to make modifications, laravel-mediable has support for creating "variants" using the Intervention library, which by be more streamlined.

**Comment by Xoshbin** [comment]
Hi @frasmage 
Thanks for replying, That's right Livewire is storing the file before passing it to the uploader. but mu issue is I can't connect the uploaded file with the model through Mediable. I did even try to use [import file](https://laravel-mediable.readthedocs.io/en/latest/uploader.html#importing-files) but it didn't work too. anyway based on you recommendation I tried to pass the uploaded file but it gave the same error

        `$media = MediaUploader::fromSource($this->file->store($directory.'/files'))->toDirectory('files/' . $directory)->onDuplicateIncrement()->upload();`

and

        `$media = MediaUploader::fromSource($this->file)->toDirectory('files/' . $directory)->onDuplicateIncrement()->upload();`

Thanks

**Comment by frasmage** [comment]
That second example should be fine. Calling `$this->file->store()` should not be necessary at all as you are effectively moving the file from temp to `$directory/files` then the uploader is duplicating it to `files/$directory` (not sure if the inversion of naming is intentional).

Can you inspect the `$this->file` variable and the output of store()? That error indicates to be that you are passing in a falsey value (e.g. empty string, false, null)

**Comment by Xoshbin** [comment]
```
$directory = "$year/$month/$day";

        Storage::makeDirectory('files/' . $directory, 0755, true, true);

        $media = MediaUploader::fromSource($this->file)->toDirectory('files/' . $directory)->onDuplicateIncrement()->upload();

```
Now it gives this error.

> fopen(/private/var/tmp/r5JwtKisqKhCYlzAQAlCj34AKJp16a-metaNC0zNC5qcGc=-.jpg): failed to open stream: No such file or directory

**Comment by frasmage** [comment]
So I'm getting a little confused because clearly this is several different runs with different files.

If you do `$this->file->store()` and then pass `$this->file` to the uploader, that missing file error error could make sense since Livewire might be purging the temp file after moving it.

You don't need to create the directory yourself, MediaUploader will do that for you.

One other thing you could try is instantiating the uploader with `$this->file->readStream()`, in case livewire has some weirdness with the pathing.

**Comment by Xoshbin** [comment]
Thank you @frasmage it worked with the 

> $this->file->readStream()

Thank you for your time

**Comment by booni3** [comment]
Old thead I know... but this worked for more (without having to re-save the file first)

```
$file = new \Symfony\Component\HttpFoundation\File\File($this->photo->getRealPath());
$uploader = MediaUploader::fromSource($file)
    ->makePrivate()
    ->toDisk('s3')
//            ->useFilename($this->photo->getFilename())
    ->toDirectory('uploads')
    ->useHashForFilename()
    ->upload();
```
