### ISSUE TITLE
Can’t remove all media from a model

### ISSUE THREAD

**Issue by Jimmylet** [plank/laravel-mediable#243]
Hello,

I'm trying to remove all media from a model.

```
$feed = Feed::where([
            ['id', $feed_id_decoded],
            ['team_id', Auth::user()->currentTeam->id]
        ])->withMediaAndVariants()->first();

$feed->media->each(function($media) {
   $media->delete();
});
$feed->delete();
```

The problem when I do this is that since there are "variants" I get a SQL conflict "Integrity constraint violation" because of the media records of the variants.

I have a model with several images attached (Feed). **I would like to remove this model, the medias and all the mediable relationships that are attached to these media.**

Is there a solution that would work?

Thank you

**Comment by frasmage** [comment]
Hi there,

So that foreign key constraint just requires you to clean up the variants before the originals.

```
$feed->media->each(function($media) {
   $original = $media->findOriginal();
   $original->getAllVariants()->each(function($variant) { $variant->delete(); });
   $original->delete();
});
$feed->delete();
```

Note, this will result in doing N+1 queries (so does your original loop), which could result in a lot of roundtrips to the database if you have a lot of media/variants attaches to your feed. You could optimize with some manual queries like `DELETE FROM media WHERE original_id IN (...)`.

**Comment by Jimmylet** [comment]
Thank you very much, your code is working !

The N + 1 problem is not important at the moment, although a better solution would be appreciated. But thank you, your package saved me a lot of time! This is one of the most useful for me!
