### ISSUE TITLE
onDuplicateReplace not working with soft deletes

### ISSUE THREAD

**Issue by vadim-isid** [plank/laravel-mediable#244]
Hi! 

I'm usign **onDuplicateReplace()** call with laravels **softDeletes** on **media**.  When I reupload the same file, it triggers the deleting system of Plank, but I saw that you makes a simple ->delete() call. 

This call will put a timestamp into  **deleted_at** column, but the data will still on table, and when Plank tries to insert a new row, it throws a duplicated QueryException "_SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry ...._".

I think that the fix of this bug is to use **->forceDelete()** function instead of simple delete at **MediaUploader:854**. 

![image](https://user-images.githubusercontent.com/61970450/105373149-a6077d80-5c06-11eb-8dbc-0fc2bdd6aafa.png)

If a user specifies onDuplicateReplace it should not make a soft delete, it should be completely deleted.

**Comment by frasmage** [comment]
Hi @vadim-isid,

Since you are intentionally soft-deleting data in all other circumstances, what is your use case for deleting it in this particular instance? This seems antithetical to the intention of soft-deletes. Would the onDuplicateUpdate behaviour not be more suitable?

On a separate note, It occurs to me that we might have another potential conflict with the Replace behaviour with variants, since those might have foreign keys to the media to be deleted.
