### ISSUE TITLE
Method Illuminate\Http\UploadedFile::file does not exist

### ISSUE THREAD

**Issue by asman03** [plank/laravel-mediable#255]
i have code:

public function store(ProductRequest $request)
    {

        if ($request->hasFile('photo')){
            
            $photos = $request->file('photo');

            foreach ($photos as $photo) {

                $data= $request->all();

                $data['slug'] = Str::slug($request->name);
                $product=Product::create($data);
                
                $uploadphoto = [
                    'products_id' => $product->id,
                    'photos' => $photo->file('photo')->store('assets/product','public')
                    // Storage::putFile('public',$request->file('photo'))
                ];
                 ProductGallery::create($uploadphoto);
            }
        }else{
            return "Image not found";
        }      
        
        return redirect()->route('dashboard-product');

    }

can you help me? thanks

**Comment by frasmage** [comment]
Hello, it does not appear like your snippet is using any part of this library. As such, you should be asking your questions in the main Laravel repository, not this one.

That said, I believe your problem is this line:

```
 'photos' => $photo->file('photo')->store('assets/product','public')
```
file() is a method of the request which you called above. You don't need to repeat it on the files.
