### ISSUE TITLE
Image Resizing/Manipulation support.

### ISSUE THREAD

**Issue by rhonz10** [plank/laravel-mediable#26]
I was reading the Docs, and I found this to have many great features. One thing I didn't see, image manipulation, or at least image resizing to thumbnails, like what Wordpress do.

Intervention/image is a very nice image manipulation library. It would be great if it will be integrated with laravel-mediable.

**Comment by frasmage** [comment]
Hi @rhonz10,

Thank you for your interest!

This question has come up before, but so far the decision has been to leave the task of image manipulation up to the user to implement, because there are many different approaches that could be taken. 

See [this thread](https://github.com/plank/laravel-mediable/issues/10) for a discussion of potential ways of integrating intervention/image. As noted in the thread, league/glide is another great option, which approaches the task from a different angle, allowing you to generate any number of sizes on the fly, without duplicating the media records themselves.

**Comment by rhonz10** [comment]
Thanks @frasmage  for the quick response. I'll take a look at league/glide. Great project by the way.
