### ISSUE TITLE
Migrations are run twice

### ISSUE THREAD

**Issue by EriBloo** [plank/laravel-mediable#301]
Hi.
This is a bit strange issue, but it seems that after publishing migrations and running `php artisan migrate` your service provider tries to run migrations twice (or once migrations from database/migrations and then from vendor).

php version 8.2
laravel 9.47
mediable 5.8.0

After commenting out `$this->loadMigrationsFrom($root . '/migrations');` in `MediableServiceProvider` published migrations are run without issues.

I noticed it because of 2 errors:
 - when I first run `php artisan migrate` I got an error that class `CreateMediableTables` is already registered. After refactoring to anonymous syntax this error was eliminated, there was no error that table `media` already exists thanks to `if (!Schema::hasTable('media'))` in migration
 - I got second error from `AddVariantsToMedia` migration that column `variant_name` already exists

I guess that `loadMigrationsFrom` is not needed if you recommend publishing migrations anyway.

**Comment by EriBloo** [comment]
Ok I found out what is a problem.
I changed migration file names (I like to keep things clean and don't like migrations jumping in random place due to timestamp). After reverting to original file name all was fixed.

Sorry for inconvenience.

**Comment by BenceSzalai** [comment]
I had the same issue just now. For some reason the migrations that are published have the date of the publication, so they do not match those in the vendor folder, so they all ran both. I had to set `'ignore_migrations'` config to fix the issue:
```php
    /**
     * Prevents loading migrations from the package.
     *
     * Use this if you are renaming the published migrations and want to prevent them from being loaded twice.
     */
    'ignore_migrations' => true,
```

The logic to publish migrations with the current date was added in #322.

But I think the publish command should automatically set `'ignore_migrations'` to `true` in the published `config/mediable.php`, because right now a fresh installation becomes a broken setup after the initial publish command.
