### ISSUE TITLE
Files being rotated during upload

### ISSUE THREAD

**Issue by booni3** [plank/laravel-mediable#303]
I am not 100% sure if this is directly related to this package. I have looked for generic PHP issues and cannot find anything.

In summary, files are being rotated randomly during upload. Either 0, 90, 180 or 270 degrees.

It seems fairly random, although some files are more consistently rotated. Manipulated images (i.e. thumbnails) are never affected.

I have tried uploading both to S3 and the local file system.

```php
$media = MediaUploader::fromSource($file)
    ->toDisk('public')
    ->toDirectory('uploads')
    ->useFilename($filename)
    ->onDuplicateUpdate()
    ->upload();
```

## 300 x 300px Manipulated Thumbnails

<img width="1057" alt="image" src="https://user-images.githubusercontent.com/20134485/219130643-8761de60-26c7-45a3-a76f-e6c80c1b583a.png">

## Full Images

<img width="1050" alt="image" src="https://user-images.githubusercontent.com/20134485/219129896-a747b0eb-b987-4a63-871a-c0dbf4045992.png">

**Comment by frasmage** [comment]
Haven't seen that one before. I don't think this is an issue with this library, since aside from providing some convenience integrations with Intervention, it doesn't manipulate any of the file contents. 

My first guess would be that there is an issue with the way the orientation metadata is encoded in the original images (e.g. by the camera) vs. how it is being interpreted by the browser. I'm assuming that Intervention is re-encoding orientation in a more compatible way when manipulating the image.

I'm not an expert with the internals of image encoding, so I don't think I can provide much more insight than the above.

**Comment by booni3** [comment]
Thanks for the quick reply! I just wanted to check you did not have any default manipulation inside the package. Sounds like you don't and something else must be going on here. Ill close this out.
