### ISSUE TITLE
URL Attribute issue with Private Buckets

### ISSUE THREAD

**Issue by sgtcoder** [plank/laravel-mediable#347]
The new URL attribute on the Plank model doesn't support signed URLs. I ended up overriding that function to get the signed/unsigned URL depending on the privacy.

**Comment by frasmage** [comment]
The `$url` attribute maps to the `getUrl()` method, which is the public URL.
It was decided against making the the `getTemporaryUrl()` method into an attribute alias as this one does not behave consistently. First, it is not idempotent (every time you access the property it will generate a new distinct URL), which is not how properties normally work. Second, the getTemporaryUrl() method takes an $expiry argument, which cannot be provided when it is an attribute.

If you really need the temporary url to be in attribute format for some reason, there is nothing stopped you from extending the Media class and adding a method like the following. Because this involves hardcoding the interval, it doesn't belong in the package itself.

```php
    public function getTemporaryUrlAttribute(): string
    {
        return $this->getTemporaryUrl(Carbon::now()->addMinutes($somePredefinedTtl));
    }
```

**Comment by sgtcoder** [comment]
I actually had added getUrlAttribute to my plank model before you had actually addeded it to your package. It autodetects if it's a url or temporary url and returns the URL based on that with 240minute time out.

And yes, data from an attribute would always be changing and not static.
