### ISSUE TITLE
Call to a member function delete() on null

### ISSUE THREAD

**Issue by ChumburidzeGio** [plank/laravel-mediable#51]
Hey,

I started using this cool package and faced with some problem, I sew in documentation that there is console command to add to database all files but I have not did it so I got error "Call to a member function delete() on null" in MediaUploader.php line 661

Its the error inside private function deleteExistingMedia(), current code is 
```
Media::where('disk', $model->disk)
            ->where('directory', $model->directory)
            ->where('filename', $model->filename)
            ->where('extension', $model->extension)
            ->first()->delete(); 
```

It can be changed maybe this way 

```
$media = Media::where('disk', $model->disk)
            ->where('directory', $model->directory)
            ->where('filename', $model->filename)
            ->where('extension', $model->extension)
            ->first();
if($media){
$media->delete();
}
```
to check for first if file is in database to not get such error

Regards,
Giorgi Chumburidze

**Comment by frasmage** [comment]
Hi @ChumburidzeGio,

It seems to me like this would be caused by your database and filesystem being out of sync, such that a duplicate file does exist on disk, but has no associated record in the database. I am not sure how you got to that state. Did you perhaps perform a [delete on the query builder](http://laravel-mediable.readthedocs.io/en/latest/media.html#deleting-media), and not the Media record itself?

I have updated the `MediaUploader` to manually delete both the record in the database and the file on disk individually, rather than depending on the media record to clean up its own file on deletion.

Thanks for pointing this out!

Sean
