### ISSUE TITLE
Chunke file uploads.

### ISSUE THREAD

**Issue by nilsenj** [plank/laravel-mediable#66]
Hello guys. First, thanks for the package.
I'm interested if there is a way of chunked file upload. It is useful when you have realy large file and sometimes filesystem doesn't really want to work with large ones.

**Comment by frasmage** [comment]
Hi @nilsenj,

Out of the box, I don't think the `MediaUploader` would be ideal for very large files, it has no particular support for chunked uploads and currently converts the stream to a string. Perhaps this could be something to add to the next version.

That said, you can use any other package of your choice (flysystem, etc.) to perform the initial upload and to place the file at its intended destination, then use `MediaUploader::import($path)` to create a media record for it. This skips some of the validation provided by the uploader, but otherwise lets you use all of the other functionality of the package (attachment, tagging, url generation, etc.).

I hope this helps!
