### ISSUE TITLE
Change default table name

### ISSUE THREAD

**Issue by liran-co** [plank/laravel-mediable#76]
Is it possible to change the default table names from 'media' and 'mediables' to something else?

**Comment by frasmage** [comment]
Hi @liran-co,

Yes it is, though you will have to make some tweaks:

- modify the migration file to rename both tables
- create a new model class extending `Plank\Mediable\Media`, set its $table property to your table name. Update config/mediable.php to set the `'model'` field to your class's FQCN.

 ```php
<?php

namespace App;

use Plank\Mediable\Media as BaseMedia;

class Media extends BaseMedia
{
    protected $table = '<YOUR_NEW_MEDIA_TABLE_HERE>'
}
```

- create a new trait, which `use`s `Plank\Mediable\Mediable`. Override the `media()` method as follows. Use this trait on all of your models instead of the default one.

 ```php
<?php

namespace App;

use Plank\Mediable\Mediable as BaseMediable;

trait Mediable
{
    use BaseMediable { media as _oldMedia }

    public function media()
    {
        return $this->morphToMany(config('mediable.model'), '<YOUR_NEW_MEDIABLE_TABLE_HERE>')
            ->withPivot('tag', 'order')
            ->orderBy('order');
    }
}
```

That should do it.

**Comment by liran-co** [comment]
This works. Thanks for your help!
