### ISSUE TITLE
Get only one media

### ISSUE THREAD

**Issue by borisdamevin** [plank/laravel-mediable#83]
Hi,

I try to find a method to get only one media on `posts` collection and not all media attach on each post.

For exemple : 

A post has many media, all with same tag. I wanna get only one of them. I suppose we need to use the `join` method, but how ?

Now a use `$posts = Post::with('media')->get();`, but I dont wanna all media.

Thank you.

**Comment by frasmage** [comment]
Hi @borisdamevin,

If I understand correctly, you have a `posts` collection, with media loaded and want to access a single media record attached to any one of the posts at a given tag?

If all posts have media attached to that tag, then `$posts->first()->firstMedia($tag)` will do. Otherwise you would need to filter down the posts to only include ones that do, either by adding conditions to the `Post` query or filtering the resulting collection first.

```php
$media = Post::whereHasMedia($tag)  // restrict to results with that media
->withMedia($tag) // eager load the media at that tag
->first() //only load one post result
->firstMedia($tag); //get the first media record attached to this post
```

or

```php
$posts = Posts::withMedia()->get(); // load all posts
$media = $posts->filter(function($post) use ($tag)  {
    return $post->hasMedia($tag); //restrict to those that have media for that tag
})->firstMedia($tag);

**Comment by borisdamevin** [comment]
Yes.

But ``firstMedia()`` work only for one ``post``, not for a collection of ```posts``.

**Comment by frasmage** [comment]
Sorry, the second example above is missing a call to `first()` on the collection. It should be `$posts->filter(...)->first()->firstMedia($tag)`.

**Comment by borisdamevin** [comment]
Ok, the filter work fine. Thank you.

But, you don't have an idea for filter ``$posts = Posts::withMedia()->get();`` directly for only select one media and not overload the database?

**Comment by frasmage** [comment]
Hi @borisdamevin, I not clear what your intention is here. From your description it sounds like you are trying to get a single media from a collection of mediables, but if that is not the case, can you be more descriptive of your needs? 

Are you trying to create a collection with one media record for each post?

**Comment by borisdamevin** [comment]
Hi,

Yes I try to get only one media on each post.

**Comment by frasmage** [comment]
Ok, that wasn't clear from your initial message. This isn't really a Mediable concern, but with Laravel collection handling.

```
$media = $posts
->filter(...) //as above, use if you want to exclude posts that do not have media at that tag
->map(function($post) use ($tag){
    return $post->firstMedia($tag);
}
```

**Comment by pet1330** [comment]
I think what you're looking to do is only fetch from the database a single `Media` model per `Post`, rather than fetching all attached `Media` and iterating through the collection to filter out all but one. In which case I think you will need to use the query builder to do something like:

```php
$PostsWithOneMedia = Post::with(['media' => function($q) {
        $q->latest()->limit(1);
    }])->get();
```

Or for a specific tag

```php
$tag = "uploaded";

$PostsWithOneMedia = Post::with(['media' => function($q) use ($tag) {
        $q->wherePivot('tag', $tag)->latest()->limit(1);
    }])->get();
```

**Comment by borisdamevin** [comment]
I finally find the good with your help.

```
$posts = Post::with(['media' => function($q){
    $q->wherePivot('tag', 'poster')->wherePivot('order', '1');
}])->get();
```

Thank for your help :). Sorry if my request was not clear.
